---
- hosts: ios-xe
  gather_facts: no
  connection: netconf
  remote_user: admin

  tasks:
  - name: establish subscription
    netconf_config:
      xml: |
          <nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
            <mdt-config-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mdt-cfg">
              <mdt-subscription>
                <subscription-id>501</subscription-id>
                <base>
                  <stream>yang-push</stream>
                  <encoding>encode-kvgpb</encoding>
                  <source-address>10.60.0.19</source-address>
                  <source-vrf>Mgmt-vrf</source-vrf>
                  <period>2000</period>
                  <xpath>/process-cpu-ios-xe-oper:cpu-usage/cpu-utilization/five-seconds</xpath>
                </base>
                <mdt-receivers>
                  <address>10.12.252.224</address>
                  <port>57500</port>
                  <protocol>grpc-tcp</protocol>
                </mdt-receivers>
              </mdt-subscription>
            </mdt-config-data>
          </nc:config>
