---
- hosts: cat9800pods
  gather_facts: no

  tasks:
   - ios_config:
      commands:
       - aaa new-model
       - aaa authorization exec default local
       - aaa authentication login default local
       - username NEW_USERNAME_HERE privilege 15 password 0 PASSWORD_HERE
       - netconf-yang
      save_when: modified
